[package]
name = "rusttester"
version = "0.1.0"
authors = ["Brady <bradypierce@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
csv = "1.1"
anyhow = "1.0"
thiserror = "1.0"
